version: '3'

services:
  postgres:
    image: postgres:13.3
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      PGPORT: 5432
    ports:
      - 15432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata

  app:
    build:
      context: .
    ports:
      - 8000:80
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    volumes:
        - ".:/app"

volumes:
  postgres_data: 